import type { KycDocument, KycEntityType, KycInvestor, KycTrack } from "./kyc";
import { requiredDocumentNames } from "./kyc";

function documents(
  prefix: string,
  entityType: KycEntityType,
  track: KycTrack,
  statuses: KycDocument["status"][],
): KycDocument[] {
  return requiredDocumentNames(entityType, track).map((name, index) => ({
    id: `${prefix}-document-${index + 1}`,
    name,
    fileUrl: statuses[index] === "missing" ? null : `/kyc/${prefix}/${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.pdf`,
    status: statuses[index] || "missing",
    rejectReason: statuses[index] === "rejected" ? "Document is unclear or no longer valid" : undefined,
  }));
}

export const KYC_DEMO_INVESTORS: KycInvestor[] = [
  {
    id: "kyc-001",
    name: "Robert Anderson",
    email: "robert.anderson@email.com",
    entityType: "individual",
    investorTrack: "foundry",
    kycStatus: "verified",
    kycSubmittedAt: "2026-09-12T09:30:00Z",
    kycVerifiedAt: "2026-09-14T14:00:00Z",
    kycLastRemindedAt: null,
    kycRemediationItems: [],
    kycProfile: { nationalId: "12345678901", bvn: "2222222222", residentialAddress: "12 Admiralty Way, Lekki Phase 1, Lagos" },
    kycDeclarations: { sourceOfFunds: "Executive Salary / Investment Income", targetTrack: "foundry" },
    kycDocuments: documents("robert", "individual", "foundry", ["approved", "approved", "approved", "approved"]),
  },
  {
    id: "kyc-002",
    name: "Jennifer White",
    email: "jennifer.white@email.com",
    entityType: "individual",
    investorTrack: "foundry",
    kycStatus: "under_review",
    kycSubmittedAt: "2026-09-28T10:45:00Z",
    kycLastRemindedAt: null,
    kycRemediationItems: [],
    kycProfile: { nationalId: "98765432109", bvn: "3333333333", residentialAddress: "5 Ozumba Mbadiwe Avenue, Victoria Island, Lagos" },
    kycDeclarations: { sourceOfFunds: "Business Proceeds / Dividends", targetTrack: "foundry" },
    kycDocuments: documents("jennifer", "individual", "foundry", ["pending", "pending", "pending", "pending"]),
  },
  {
    id: "kyc-003",
    name: "Thomas Harris",
    email: "thomas.harris@email.com",
    entityType: "individual",
    investorTrack: "foundry",
    kycStatus: "remediation_required",
    kycSubmittedAt: "2026-09-21T16:20:00Z",
    kycLastRemindedAt: "2026-09-29T09:00:00Z",
    kycRemediationItems: ["Live Biometric Selfie — image is unclear", "Proof of Address — upload a document issued within three months"],
    kycProfile: { nationalId: "45678912304", bvn: "4444444444", residentialAddress: "23 Adjose Street, Surulere, Lagos" },
    kycDeclarations: { sourceOfFunds: "Savings / Salary", targetTrack: "foundry" },
    kycDocuments: documents("thomas", "individual", "foundry", ["approved", "rejected", "missing", "approved"]),
  },
  {
    id: "kyc-004",
    name: "Clark Family Office",
    email: "compliance@clarkfamilyoffice.com",
    entityType: "family-office",
    investorTrack: "foundry",
    kycStatus: "under_review",
    kycSubmittedAt: "2026-09-30T11:10:00Z",
    kycLastRemindedAt: null,
    kycRemediationItems: [],
    kycProfile: { companyName: "Clark Family Office Ltd", rcNumber: "RC-1298410", companyAddress: "3 Glover Road, Ikoyi, Lagos", repName: "Patricia Clark", repEmail: "patricia.clark@email.com" },
    kycDeclarations: { declaredAumRange: "$50M - $100M AUM", targetTrack: "foundry" },
    kycDocuments: documents("clark-family", "family-office", "foundry", ["pending", "pending", "pending", "pending"]),
  },
  {
    id: "kyc-005",
    name: "Ogunlesi Holdings",
    email: "compliance@ogunlesiholdings.com",
    entityType: "family-office",
    investorTrack: "foundry",
    kycStatus: "pending",
    kycSubmittedAt: null,
    kycLastRemindedAt: "2026-09-25T11:00:00Z",
    kycRemediationItems: [],
    kycProfile: { companyName: "Ogunlesi Holdings Ltd", rcNumber: "RC-1445092", companyAddress: "", repName: "Adebayo Ogunlesi", repEmail: "" },
    kycDeclarations: { declaredAumRange: "$10M - $50M AUM", targetTrack: "" },
    kycDocuments: documents("ogunlesi", "family-office", "foundry", ["pending", "missing", "missing", "missing"]),
  },
  {
    id: "kyc-006",
    name: "Zenith Capital Partners",
    email: "kyc@zenithcapital.com",
    entityType: "institution",
    investorTrack: "foundry",
    kycStatus: "under_review",
    kycSubmittedAt: "2026-10-02T10:30:00Z",
    kycLastRemindedAt: null,
    kycRemediationItems: [],
    kycProfile: { companyName: "Zenith Capital Partners Ltd", rcNumber: "RC-1182004", companyAddress: "1410 Akin Adesola Street, Victoria Island, Lagos", repName: "Grace Adeyemi", repEmail: "g.adeyemi@zenithcapital.com", institutionType: "Investment Managers & Funds", structure: "Real Estate Fund", aumRange: "₦50B–₦250B", horizon: "3–7 years", sectors: ["Commercial", "Infrastructure"], regulatoryStatus: "Regulated" },
    kycDeclarations: {},
    kycDocuments: documents("zenith", "institution", "foundry", Array(7).fill("pending")),
  },
  {
    id: "kyc-007",
    name: "Meridian Pension Trust",
    email: "onboarding@meridianpension.com",
    entityType: "institution",
    investorTrack: "foundry",
    kycStatus: "pending",
    kycSubmittedAt: null,
    kycLastRemindedAt: null,
    kycRemediationItems: [],
    kycProfile: { companyName: "Meridian Pension Trust", rcNumber: "RC-1057788", companyAddress: "27 Aguiyi Ironsi Street, Maitama, Abuja", repName: "Ibrahim Suleiman", repEmail: "", institutionType: "Pension Funds", structure: "", aumRange: "₦250B–₦1T", horizon: "7+ years", sectors: [], regulatoryStatus: "Regulated" },
    kycDeclarations: {},
    kycDocuments: documents("meridian", "institution", "foundry", ["pending", "pending", "pending", "pending", "pending", "missing", "missing"]),
  },
  {
    id: "kyc-008",
    name: "Emeka Obi",
    email: "emeka.obi@email.com",
    entityType: "individual",
    investorTrack: "harbor",
    kycStatus: "failed",
    kycSubmittedAt: "2026-09-18T13:05:00Z",
    kycLastRemindedAt: null,
    kycRemediationItems: ["Government Photo ID — expired; upload a valid passport or NIN slip"],
    kycProfile: { nationalId: "32165498703", bvn: "6666666666", residentialAddress: "9 Acme Road, Ogba, Ikeja, Lagos" },
    kycDeclarations: { sourceOfFunds: "Contracting Income", targetTrack: "harbor" },
    kycDocuments: documents("emeka", "individual", "harbor", ["rejected", "approved", "approved", "approved"]),
  },
];
